#   é…ç½®ç¼–è¾‘å™¨æ ¼å¼è§„åˆ™
#
# 1. æ•°ç»„ç±»å‹éœ€è¦ åœ¨è¡Œæ³¨é‡Šåæ·»åŠ  ç±»å‹ç”³æ˜  eg: <string[]>  <object[]>
#   1.1 å¦‚æœå…ƒç´ æ˜¯å¯¹è±¡ç»“æ„éœ€è¦å£°æ˜æ•°æ®ç»“æ„, ç»“æ„éµå¾ª json æ ¼å¼  {{"xx":"xx"}}
#   1.2 å¦‚æœå…ƒç´ å¯¹è±¡æ˜¯é€’å½’åµŒå¥—çš„ å¯ä»¥ç”¨ç©ºæ•°ç»„æ ‡è¯† {{"xx:æ ‡é¢˜":"xx","ff:æ ‡é¢˜":[]}} , ff å­—æ®µç»“æ„è¡¨ç¤ºå’Œ æœ¬èº«ä¸€è‡´
# 2. æšä¸¾å±æ€§å£°æ˜æ ¼å¼ eg:  <[enum,enum]>
# 3. ç¼–è¾‘å™¨ä¸­å±æ€§åç§°æ ‡æ³¨, åªéœ€åœ¨å±æ€§å­—æ®µå æ·»åŠ æ³¨é‡Š
# 4. éœ€è¦è·³è¿‡å½“å‰å±æ€§, åªéœ€è¦åœ¨æ³¨é‡Šä¸Š æ·»åŠ ä¸¤ä¸ª ##
# 5. å­—æ®µé»˜è®¤æ²¡å€¼æ—¶, åˆ™å¿…é¡»åœ¨åé¢æ·»åŠ  å¤‡æ³¨ä¿¡æ¯


# Open Graph protocol | OG åè®®
open_graph: true # å¯ç”¨

top_bars:
  - title: menu.sites.site
    url: '#'
    children:
      - title: menu.archives
        url: /archives/
      - title: menu.sites.categories
        url: /categories/
      - title: menu.sites.tags
        url: /tags/
  - title: menu.links
    url: '#'
    children:
      - title: å‹äººå¸
        url: /link/
      - title: ç•™è¨€æ¿
        url: /comments/

favicon:
  logo: /images/siteicon/favicon.ico
  icon16: /images/siteicon/favicon-16x16.png
  icon32: /images/siteicon/favicon-32x32.png
  apple_touch_icon: /images/siteicon/apple-touch-icon.png
  webmanifest: /manifest.json
  visibilitychange: true
  hidden: /images/siteicon/favicon.ico
  show_text: é‚£äººå´åœ¨ï¼Œç¯ç«é˜‘çŠå¤„
  hide_text: ä¼—é‡Œå¯»ä»–åƒç™¾åº¦ï¼Œè“¦ç„¶å›é¦–

# User info | ç”¨æˆ·ä¿¡æ¯
user:
  name: ç‹ä¹å¼¦SZÂ·Ninty # Nickname | æ˜µç§°
  first_name: é­”æ³•å±‹ # å
  last_name: æ±å¡” # å§“
  email: email@sinzmise.top # email | ç”µå­é‚®ç®±
  domain: 'https://blog.sinzmise.top/' # Domain | ç«™ç‚¹åŸŸå
  avatar: /img/avatar.png # Avatar | ç«™ç‚¹å¤´åƒ
  describe: ç§ä¸‹ä¸€é¢—æœ‰æ•…äº‹çš„ç§å­ï¼Œè®©å®ƒå¸¦ç€é­”æ³•å’Œå¥‡è¿¹ç”Ÿæ ¹å‘èŠ½ # Describe | ç½‘ç«™ç®€ä»‹
  rule_text: 1.ç«™ç‚¹å¯ä»¥åœ¨ä¸­å›½å¤§é™†åŒºåŸŸæ­£å¸¸è®¿é—®ä¸”å†…å®¹ç¬¦åˆä¸­å›½å¤§é™†æ³•å¾‹æ³•è§„<br>2.ç«™ç‚¹å‹æƒ…é“¾æ¥å«æœ¬ç«™é“¾æ¥<br>3.ç«™ç‚¹ç±»å‹ä¸ºåšå®¢ï¼ˆé™¤æˆ‘ä¸»åŠ¨ç”³è¯·çš„é“¾æ¥ä¹‹å¤–ï¼‰ # å‹é“¾è§„åˆ™

sw: true

comment:
  use:
    - Twikoo

  twikoo:
    envId: https://tk.pl.blog.sinzmise.top/ # è…¾è®¯äº‘ç¯å¢ƒid

  artalk:
    server: https://atk.pl.blog.sinzmise.top/
    site: æ˜Ÿç©ºæ•…äº‹Â·é­”æ³•å°å±‹

# Banner settings | æ¨ªå¹…é…ç½®
banner:
  use_cover: true # Use the cover image for article details | æ–‡ç« è¯¦æƒ…ä½¿ç”¨å°é¢å›¾
  danmu: # danmu | å¼¹å¹•
    enable: true # enable | å¯ç”¨
    el: .trm-banner # el | å¼¹å¹•å®¹å™¨
  default: # é»˜è®¤æ¨ªå¹…é…ç½®
    type: img # æ¨ªå¹…ç±»å‹ <[img,slideshow,video]>
    bgurl: /img/banner.png # èƒŒæ™¯å›¾åœ°å€
    banner_text: Hi my new friend! # æ¨ªå¹…æè¿°
    position: top # åŒ CSS object-position
    fit: cover # åŒ CSS object-fit
  index: ## é¦–é¡µæ¨ªå¹…
    banner_title: ç§ä¸‹ä¸€é¢—æœ‰æ•…äº‹çš„ç§å­<br>è®©å®ƒå¸¦ç€é­”æ³•å’Œå¥‡è¿¹ç”Ÿæ ¹å‘èŠ½
    banner_text: Welcome to Ceta Storical Houseï¼
  archive: ## å½’æ¡£é¡µæ¨ªå¹…
    banner_title: äº‘é—´è¿ä¸‹æ¦»ï¼Œ<br>å¤©ä¸Šæ¥è¡Œæ¯ã€‚
    banner_text: The article archive
  links: ## å‹é“¾é¡µæ¨ªå¹…
    banner_title: è«æ„å‰è·¯æ— çŸ¥å·±ï¼Œ<br>å¤©ä¸‹è°äººä¸è¯†å›ã€‚
    banner_text: A link to a friend's website
  comment: ## è¯„è®ºé¡µæ¨ªå¹…
    banner_title: é†‰åä¸çŸ¥å¤©åœ¨æ°´ï¼Œ<br>æ»¡èˆ¹æ¸…æ¢¦å‹æ˜Ÿæ²³ã€‚
    banner_text: The magic tree hole
  about: ## å…³äºé¡µæ¨ªå¹…
    banner_title: é†‰åä¸çŸ¥å¤©åœ¨æ°´ï¼Œ<br>æ»¡èˆ¹æ¸…æ¢¦å‹æ˜Ÿæ²³ã€‚
    banner_text: About me

sidebar:
  social: # ç¤¾äº¤åœ°å€
    - name: RSS
      icon: fas fa-rss
      url: atom.xml
    - name: Github
      icon: fab fa-github
      url: https://github.com/SinzMise
  info: # ä¸ªäººä¿¡æ¯
    - key: é‚®ä»¶
      class: u-email
      val: email@sinzmise.top
    - key: çœä»½
      class: p-region
      val: å¹¿ä¸œ
    - key: åŸå¸‚
      class: p-locality
      val: æ½®å·

# Blog search | æœç´¢
search:
  enable: true # å¯ç”¨
  type: docsearch # æœç´¢ç±»å‹ <[local,engine,docsearch]>
  docsearch:
    appId: QAS05YI2PH # see email
    apiKey: 67ffd4c9fa1234148ec4f8b27dfdb2a7 # see email
    indexName: sinzmise # see email

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled | Swup æ’ä»¶
swup: true # å¯ç”¨

assets:
  third_party_provider: https://jsd.cdn.storisinz.site/npm
  plugin:
    # Waline
    waline_js: https://jsd.cdn.storisinz.site/npm/@waline/client@v3/dist/waline.js
    waline_css: https://jsd.cdn.storisinz.site/npm/@waline/client@v3/dist/waline.css
    # Artalk
    artalk_js: https://jsd.cdn.storisinz.site/npm/artalk/dist/Artalk.js
    artalk_css: https://jsd.cdn.storisinz.site/npm/artalk/dist/Artalk.css
    # DocSearch
    docsearch_css: https://jsd.cdn.storisinz.site/npm/@docsearch/css/dist/style.min.css
    docsearch_js: https://jsd.cdn.storisinz.site/npm/@docsearch/js/dist/umd/index.min.js

wordcount:
  enable: true
  count: true
  time: true

footer:
  copyright_year: 2021
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 12/17/2021 14:53:00
  custom_text:
    top:
      <a href="https://xn--sr8hvo.ws/previous">â†</a>
      An&nbsp;<a href="https://xn--sr8hvo.ws">IndieWeb Webring</a>&nbsp;ğŸ•¸ğŸ’
      <a href="https://xn--sr8hvo.ws/next">â†’</a>
    bottom:
      <p>
      <a href="https://icp.gov.moe/?keyword=20231033" target="_blank">èŒICPå¤‡20231033å·</a>&nbsp;|
      <a target="_blank" href="https://beian.miit.cn.com/gov/search.php?query=blog.sinzmise.top" title="MIITå¤‡20240818å·">MIITå¤‡20240818å·</a>&nbsp;|
      <a href="https://guan.ma/hao/2024000155/" title="å®˜ç 2024000155å·"><img src="https://style.wmou.com/images/guanma.png" alt="å®˜ç " width="9">å®˜ç 2024000155å·</a>
      </p>
      <p>
      <span>æˆ‘åŠ å…¥çš„ï¼š</span>
      <a href="https://zhblogs.ohyee.cc/" target="_blank">ä¸­æ–‡åšå®¢åˆ—è¡¨</a>&nbsp;|
      <a href="https://storeweb.cn/member/o/1585" target="_blank">ä¸ªç«™å•†åº—</a>&nbsp;|
      <a href="https://bf.zzxworld.com/s/995" target="_blank">BlogFinder</a>&nbsp;|
      <a href="https://sites.link/site-info?siteType=life&siteId=64cb373190e35300a8eec654" target="_blank">ç«™ç‚¹èšåˆå¹³å°</a>&nbsp;|
      <a href="https://boke.lu" target="_blank">åšå®¢å½•</a>&nbsp;|
      <a href="https://rssblog.cn/member/d711afd659d65c2ba2d3b18697818cf7/" target="_blank">RssBlog</a>&nbsp;|
      <a href="https://blogscn.fun" target="_blank">ç¬”å¢¨è¿¹</a>&nbsp;|
      <a href="https://forever.dreamerhe.cn/" target="_blank">æ¢¦å¢ƒåˆ—è½¦</a>&nbsp;|
      <a href="https://firewood.news/" target="_blank">ç§¯è–ª</a>&nbsp;|
      <a href="https://daohang.lusongsong.com/" target="_blank">åšå®¢å¤§å…¨</a>
      </p>

layout:
  head: async/_partial/head # headå— v2.1.11 +
  footer: async/_partial/footer # é¡µè„šæ¨¡æ¿
  sidebar: async/_partial/sidebar/index # ä¾§æ æ¨¡æ¿
  banner: async/_partial/banner # é¡¶éƒ¨æ¨ªå¹…æ¨¡æ¿
  main: async/_partial/main # æ•´ä½“å¸ƒå±€ç»“æ„æ¨¡æ¿
  script: async/_partial/script # è„šæœ¬å— v2.1.11 +

  post_info: async/_partial/post/post-info # æ–‡ç« ä¿¡æ¯æ¨¡æ¿
  post_content: async/_partial/post/post-content # æ–‡ç« å†…å®¹æ¨¡æ¿

  comment: async/_third-party/comment/index # è¯„è®ºæ’ä»¶æ¨¡æ¿

  sidebar_user: async/_partial/sidebar/card/user # ä¾§æ  - ç”¨æˆ·å¤´åƒæ¨¡æ¿
  sidebar_social: async/_partial/sidebar/card/social # ä¾§æ  - ç¤¾äº¤å›¾æ ‡æ¨¡å—
  sidebar_info: async/_partial/sidebar/card/info # ä¾§æ  - ç”¨æˆ·ä¿¡æ¯æ¨¡å—

  page_links: async/_partial/page/links # å‹é“¾é¡µé¢æ¨¡å—

  search: async/_widget/search # æœç´¢å¡ç‰‡æ¨¡æ¿ v2.1.11 +
  header_search: async/_widget/header-search # é¡¶éƒ¨èœå•-æŸ¥è¯¢éƒ¨åˆ†